NUMPY


In [ ]:
import numpy as np
a=np.zeros(3)
type(a[0])

numpy.float64

In [ ]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z.shape

(10,)

In [ ]:
z=np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
z=np.empty(3)
z

array([0., 0., 0.])

In [ ]:
z = np.linspace(1,7,5)
z

array([1. , 2.5, 4. , 5.5, 7. ])

In [ ]:
z=np.array([10,20,30,443])
z

array([ 10,  20,  30, 443])

In [ ]:
a_list=[[1,2,3,4],[5,3,2,8]]
z=np.array(a_list)
z

array([[1, 2, 3, 4],
       [5, 3, 2, 8]])

In [ ]:
z.shape

(2, 4)

In [ ]:
z1=np.random.randint(5,15,size=6)
z1

array([ 8,  7, 12,  7,  5,  5])

In [ ]:

z1[-1]

5

In [ ]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a<3

array([ True,  True, False, False, False])

In [ ]:
a>3

array([False, False, False,  True,  True])

In [ ]:
z[z>3]

array([4, 5])

In [ ]:
b_array=np.array([1,2,3,4,5])
c_array=np.array([6,7,8,9,10])

In [ ]:
b_array + c_array

array([ 7,  9, 11, 13, 15])

In [ ]:
b_array + 10

array([11, 12, 13, 14, 15])

In [ ]:
b_array * c_array

array([ 6, 14, 24, 36, 50])

In [ ]:
b_array * 10

array([10, 20, 30, 40, 50])

In [ ]:
b_array @ c_array

130

In [ ]:
d=np.array([6,9,2,0,3,5])
np.sort(d)

array([0, 2, 3, 5, 6, 9])